import ArlibCommunity.Probability.ContCoinProto
import ArlibCommunity.Probability.DeltaIndependence
import ArlibCommunity.Probability.DependenceCovariance
import ArlibCommunity.Probability.EmpiricalFrequency
import ArlibCommunity.Probability.FailureAmplification
import ArlibCommunity.Probability.FirstBad
import ArlibCommunity.Probability.InverseCDF
import ArlibCommunity.Probability.Median
import ArlibCommunity.Probability.MixedCoinSpace
import ArlibCommunity.Probability.MixedCondCELinear
import ArlibCommunity.Probability.MixedCondProd
import ArlibCommunity.Probability.MixedCoordIndep
import ArlibCommunity.Probability.MixedRunProduct
import ArlibCommunity.Probability.NuIndepTensor
import ArlibCommunity.Probability.PoissonSplitting
import ArlibCommunity.Probability.PolyHash
import ArlibCommunity.Probability.Reduce
import ArlibCommunity.Probability.RobbinsMonro
import ArlibCommunity.Probability.RunProduct
import ArlibCommunity.Probability.SequentialDominate
import ArlibCommunity.Probability.StochasticApproximation
import ArlibCommunity.Probability.UniformCoin

/-! Algorithm-facing modules extracted from `Arlib.Probability`. -/
